In [32]:
import numpy as np
import pandas as pd
import sys,os

def load_files(batch):
    images = []
    labels = []
    for i in batch:
        print('Loading File: ' + i)
        x = np.load(i,encoding = 'latin1',allow_pickle=True).item()
        keys = x.keys()
        for key in keys:
            images.append(x[key][0])
            labels.append(x[key][1])
    return np.array(images),np.array(labels)

def get_feature(labels,feature):
    feature_values = []
    for i in labels:
        feature_values.append(i[feature])
    feature_values = np.array(feature_values)
    return feature_values

def get_cos_values(zenith,azimuth):
    cos1 = []
    cos2 = []
    cos3 = []
    for i,j in zip(zenith,azimuth):
        cos1.append(np.sin(i) * np.cos(j))
        cos2.append(np.sin(i) * np.sin(j))
        cos3.append(np.cos(i))
    return np.array(cos1),np.array(cos2),np.array(cos3)

In [33]:
file_path = '/fs/scratch/PAS1495/amedina/'
y = os.listdir(file_path+'processed_simple')

file_names = []

for i in y:
    file_names.append(file_path+'processed_simple/'+i)

file_names_batched = list(np.array_split(file_names,5))

In [34]:
images1,labels = load_files(file_names_batched[0])

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5958.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_207.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5774.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5256.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4768.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2519.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4632.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5356.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4155.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5633.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4163.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7039.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6819.npy
Loading File: /fs/scratch/

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5011.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_719.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1538.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_496.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6844.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2295.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7850.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5971.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1227.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4001.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4573.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2758.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6983.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2293.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1825.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2386.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3870.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5659.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5055.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3956.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4430.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_722.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4261.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_384.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1188.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7905.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6385.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2609.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_242.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7362.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6221.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5129.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7624.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6743.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3165.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_981.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5088.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2710.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1661.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1023.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3332.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3027.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1664.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_547.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_948.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2924.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6092.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2636.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5479.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4426.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6211.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7270.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1071.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_334.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4009.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3035.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7751.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5346.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5648.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_644.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1663.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_525.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2381.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4161.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_817.npy
Loading File: /fs/scratch/PAS

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6990.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2728.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6078.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4037.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4505.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6629.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6072.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3729.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1291.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2643.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6987.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3006.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2247.npy
Loading File: /fs/scratch

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_864.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7904.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5661.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1103.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2602.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7359.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6588.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_470.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_163.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7857.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4894.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1872.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5619.npy
Loading File: /fs/scratch/PA

KeyboardInterrupt: 

In [25]:
images = images1[:,:,:,:]
#images = images1


zenith_values = get_feature(labels,1)
azimuth_values = get_feature(labels,2)

zenith_direction = []

for i in zenith_values:
    if i < np.pi/2.0:
        zenith_direction.append(0)
    if i >= np.pi/2.0:
        zenith_direction.append(1)

cos1,cos2,cos3 = get_cos_values(zenith_values,azimuth_values)

In [26]:
import tensorflow as tf

import keras
from keras.models import Sequential,load_model, Model
from keras.layers import Dense, Dropout, Flatten, Input,InputLayer, Concatenate
from keras.layers import SeparableConv2D, MaxPooling2D , GaussianNoise,BatchNormalization
from keras import backend as K
from sklearn.model_selection import train_test_split,KFold
from keras.layers import LeakyReLU,GaussianDropout,Lambda,UpSampling1D, LSTM
from keras import regularizers

In [27]:
cos_values = np.array(list(zip(cos1,cos2,cos3)))
cos_values1 = np.zeros([len(cos_values),len(cos_values[0])])
for i in range(len(cos_values)):
    for j in range(len(cos_values[0])):
        cos_values1[i][j]=(cos_values[i][j] + 1.0)/2.0
print(cos_values1)

[[0.60534236 0.01458017 0.44281103]
 [0.12694781 0.79961908 0.64512226]
 [0.82456251 0.27577657 0.80721822]
 ...
 [0.30552944 0.60858995 0.94764877]
 [0.65875653 0.02868605 0.44842938]
 [0.41665837 0.74977711 0.92504773]]


In [28]:
def get_data(images,values):
    x_train, x_test , y_train , y_test = train_test_split(np.array(zip(images,zenith_direction)),values,test_size = 0.1 , random_state=42)
    return x_train,x_test,y_train,y_test

x_train,x_test,y_train,y_test = get_data(images,cos_values1)

In [16]:
number_features=9

img_heights,img_rows = 60,86

kernel = 3
kernel2 = 2

batch_size = 128
epochs=20

model1_input = Input(shape=(number_features,img_heights,img_rows))

model1 = LeakyReLU(alpha = 0.01)(model1_input)
output1 = MaxPooling2D(kernel2,padding='same',data_format='channels_first')(model1)
model1 = SeparableConv2D(32,kernel,padding='same',kernel_regularizer=regularizers.l2(0.01),data_format='channels_first')(output1)

model1 = LeakyReLU(alpha = 0.01)(model1)
output2 = MaxPooling2D(kernel2,padding='same',data_format='channels_first')(model1)
model1 = SeparableConv2D(32,kernel,padding='same',kernel_regularizer=regularizers.l2(0.01),data_format='channels_first')(output2)

model1 = LeakyReLU(alpha = 0.01)(model1)
output3 = MaxPooling2D(kernel2,padding='same',data_format='channels_first')(model1)
model1 = SeparableConv2D(32,kernel,padding='same',kernel_regularizer=regularizers.l2(0.01),data_format='channels_first')(output3)

cnn_model1 = Flatten()(model1_input)
cnn_model2 = Flatten()(model1)
cnn_model3 = Flatten()(output1)
cnn_model4 = Flatten()(output2)
cnn_model5 = Flatten()(output3)
direction_model = Concatenate(axis=-1)([cnn_model1,
                                cnn_model2,
                                cnn_model3,
                                cnn_model4,
                                cnn_model5
                                ])

direction_model = Dense(60,activation='relu')(direction_model)
prediction = Dense(1,activation='sigmoid')(direction_model)


direction_model = Model(inputs=model1_input,outputs=prediction)
opt = keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-8, decay=1e-5, amsgrad=False)
direction_model.compile(optimizer=opt , loss = 'binary_crossentropy',metrics=['accuracy'])
print(direction_model.summary())

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 9, 60, 86)    0                                            
__________________________________________________________________________________________________
leaky_re_lu_1 (LeakyReLU)       (None, 9, 60, 86)    0           input_1[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 9, 30, 43)    0           leaky_re_lu_1[0][0]              
__________________________________________________________________________________________________
separable_conv2d_1 (SeparableCo (None, 32, 30, 43)   401         max_pooling2d_1[0][0]            
__________________________________________________________________________________________________
leaky_re_l

In [17]:
direction_model.fit(np.array(zip(*x_train)[0]), np.array(zip(*x_train)[1]),
                      batch_size=batch_size,
                      epochs=epochs,
                      verbose=1,
                      validation_data=(np.array(zip(*x_test)[0]), np.array(zip(*x_test)[1]))
                   )

Train on 10158 samples, validate on 1129 samples
Epoch 1/20
10158/10158 [==============================] - 10s 947us/step - loss: 0.3607 - acc: 0.8658 - val_loss: 0.3567 - val_acc: 0.8556
Epoch 2/20
10158/10158 [==============================] - 8s 830us/step - loss: 0.2674 - acc: 0.8887 - val_loss: 0.3092 - val_acc: 0.8618
Epoch 3/20
10158/10158 [==============================] - 9s 844us/step - loss: 0.2159 - acc: 0.9069 - val_loss: 0.2748 - val_acc: 0.8751
Epoch 4/20
10158/10158 [==============================] - 9s 888us/step - loss: 0.1776 - acc: 0.9219 - val_loss: 0.2344 - val_acc: 0.8919
Epoch 5/20
10158/10158 [==============================] - 9s 886us/step - loss: 0.1448 - acc: 0.9442 - val_loss: 0.2074 - val_acc: 0.9167
Epoch 6/20
10158/10158 [==============================] - 10s 954us/step - loss: 0.1157 - acc: 0.9654 - val_loss: 0.1789 - val_acc: 0.9309
Epoch 7/20
10158/10158 [==============================] - 9s 915us/step - loss: 0.0925 - acc: 0.9785 - val_loss: 0.1578 -

In [29]:
direction_model = load_model('/users/PAS1495/amedina/work/DNN_Project/script/Network/direction_model.h5')

predict = direction_model.predict(images)
values = []
for i in predict:
    if i < 0.5:
        values.append(0.0)
    elif i >= 0.5:
        values.append(1.0)

In [30]:
predict.shape

(22650, 1)

In [31]:
from sklearn import metrics
matrix = metrics.confusion_matrix(zenith_direction[0:22650],values)
print(matrix)

[[19419   144]
 [ 1174  1913]]


In [21]:
direction_model.save('direction_model.h5')