In [1]:
import numpy as np
import pandas as pd
import sys,os

def load_files(batch):
    images = []
    labels = []
    for i in batch:
        print('Loading File: ' + i)
        x = np.load(i,encoding = 'latin1',allow_pickle=True).item()
        keys = x.keys()
        for key in keys:
            images.append(x[key][0])
            labels.append(x[key][1])
    return np.array(images),np.array(labels)

def get_feature(labels,feature):
    feature_values = []
    for i in labels:
        feature_values.append(i[feature])
    feature_values = np.array(feature_values)
    return feature_values

def get_cos_values(zenith,azimuth):
    cos1 = []
    cos2 = []
    cos3 = []
    for i,j in zip(zenith,azimuth):
        cos1.append(np.sin(i) * np.cos(j))
        cos2.append(np.sin(i) * np.sin(j))
        cos3.append(np.cos(i))
    return np.array(cos1),np.array(cos2),np.array(cos3)

In [2]:
file_path = '/fs/scratch/PAS1495/amedina/'
y = os.listdir(file_path+'processed_simple')

file_names = []

for i in y:
    file_names.append(file_path+'processed_simple/'+i)

file_names_batched = list(np.array_split(file_names,15))

In [3]:
images1,labels = load_files(file_names_batched[0])

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5958.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_207.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5774.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5256.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4768.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2519.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4632.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5356.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4155.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5633.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4163.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7039.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6819.npy
Loading File: /fs/scratch/

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3927.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5011.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_719.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1538.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_496.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6844.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2295.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7850.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5971.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1227.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4001.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4573.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2758.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2584.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2293.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1825.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2386.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3870.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5659.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5055.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3956.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4430.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_722.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4261.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_384.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1188.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1167.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6385.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2609.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_242.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7362.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6221.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5129.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_7624.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6743.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3165.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_981.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5088.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2710.npy
Loading File: /fs/scratch/P

Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4399.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1023.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3332.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_3027.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_1664.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_547.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_948.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2924.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6092.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_2636.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_5479.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_4426.npy
Loading File: /fs/scratch/PAS1495/amedina/processed_simple/images_6211.npy
Loading File: /fs/scratch/P

In [4]:
images = images1[:,:,:,:]


zenith_values = get_feature(labels,1)
azimuth_values = get_feature(labels,2)

#cos1,cos2,cos3 = get_cos_values(zenith_values,azimuth_values)

In [5]:
zenith_check = list(zip(images,zenith_values,azimuth_values))
new_images = []
new_zenith_values = []
new_azimuth_values = []
for i in zenith_check:
    if i[1] < np.pi/2.0:
        new_images.append(i[0])
        new_zenith_values.append(i[1])
        new_azimuth_values.append(i[2])

cos1,cos2,cos3=get_cos_values(new_zenith_values,new_azimuth_values)

In [6]:
import tensorflow as tf

import keras
from keras.models import Sequential,load_model, Model
from keras.layers import Dense, Dropout, Flatten, Input,InputLayer, Concatenate
from keras.layers import SeparableConv2D, MaxPooling2D , GaussianNoise,BatchNormalization
from keras import backend as K
from sklearn.model_selection import train_test_split,KFold
from keras.layers import LeakyReLU,GaussianDropout,Lambda,UpSampling1D, LSTM
from keras import regularizers

Using TensorFlow backend.


In [7]:
cos_values = np.array(list(zip(cos1,cos2,cos3)))
cos_values1 = np.zeros([len(cos_values),len(cos_values[0])])
for i in range(len(cos_values)):
    for j in range(len(cos_values[0])):
        cos_values1[i][j]=(cos_values[i][j] + 1.0)/2.0
print(cos_values1)

[[0.12694781 0.79961908 0.64512226]
 [0.82456251 0.27577657 0.80721822]
 [0.17906406 0.41434649 0.87371594]
 ...
 [0.41185121 0.84000313 0.85584781]
 [0.30552944 0.60858995 0.94764877]
 [0.41665837 0.74977711 0.92504773]]


In [8]:
def get_data(images,values):
    x_train, x_test , y_train , y_test = train_test_split(np.array(images),values,test_size = 0.1 , random_state=42)
    return x_train,x_test,y_train,y_test

x_train,x_test,y_train,y_test = get_data(new_images,cos_values1)

In [9]:
def loss_space_angle(y_true,y_pred):
    y_true1 = y_true*2.0-1.0
    y_pred1 = y_pred*2.0-1.0
    subtraction = tf.math.subtract(y_true1,y_pred1)
    y = tf.matrix_diag_part(K.dot(subtraction,K.transpose(subtraction)))
    loss = tf.math.reduce_mean(y)
    return loss


In [10]:
number_features = 9

img_heights,img_rows = 60,86

kernel = 3
kernel2 = 2

model1_input = Input(shape=(number_features,img_heights,img_rows))

model1 = LeakyReLU(alpha = 0.01)(model1_input)
output1 = MaxPooling2D(kernel2,padding='same',data_format='channels_first')(model1)
model1 = SeparableConv2D(32,kernel,padding='same',kernel_regularizer=regularizers.l2(0.01),data_format='channels_first')(output1)

model1 = LeakyReLU(alpha = 0.01)(model1)
output2 = MaxPooling2D(kernel2,padding='same',data_format='channels_first')(model1)
model1 = SeparableConv2D(32,kernel,padding='same',kernel_regularizer=regularizers.l2(0.01),data_format='channels_first')(output2)

model1 = LeakyReLU(alpha = 0.01)(model1)
output3 = MaxPooling2D(kernel2,padding='same',data_format='channels_first')(model1)
model1 = SeparableConv2D(32,kernel,padding='same',kernel_regularizer=regularizers.l2(0.01),data_format='channels_first')(output3)

cnn_model1 = Flatten()(model1_input)
cnn_model2 = Flatten()(model1)
cnn_model3 = Flatten()(output1)
cnn_model4 = Flatten()(output2)
cnn_model5 = Flatten()(output3)
cnn_model = Concatenate(axis=-1)([cnn_model1,
                                cnn_model2,
                                cnn_model3,
                                cnn_model4,
                                cnn_model5
                                ])


cnn_model = Model(inputs=model1_input,outputs=cnn_model)
opt = keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-8, decay=1e-5, amsgrad=False)
cnn_model.compile(optimizer=opt , loss = loss_space_angle)

print(cnn_model.summary())

W0820 15:57:04.647689 47630012646720 deprecation_wrapper.py:119] From /users/PAS1495/amedina/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0820 15:57:04.661274 47630012646720 deprecation_wrapper.py:119] From /users/PAS1495/amedina/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 15:57:04.664793 47630012646720 deprecation_wrapper.py:119] From /users/PAS1495/amedina/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0820 15:57:04.666270 47630012646720 deprecation_wrapper.py:119] From /users/PAS1495/amedina/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Ple

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 9, 60, 86)    0                                            
__________________________________________________________________________________________________
leaky_re_lu_1 (LeakyReLU)       (None, 9, 60, 86)    0           input_1[0][0]                    
__________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)  (None, 9, 30, 43)    0           leaky_re_lu_1[0][0]              
__________________________________________________________________________________________________
separable_conv2d_1 (SeparableCo (None, 32, 30, 43)   401         max_pooling2d_1[0][0]            
__________________________________________________________________________________________________
leaky_re_l

In [11]:
input_new = Input(shape=(number_features,img_heights,img_rows))

output = Lambda(lambda x: cnn_model(x))(input_new)

model = Dropout(0.5)(output)
model = Dense(512)(model)
model = LeakyReLU(alpha = 0.01)(model)
model = Dropout(0.5)(model)
model = Dense(512)(model)
model = LeakyReLU(alpha = 0.01)(model)

input_new_prime = Flatten()(input_new)
model = Concatenate(axis=-1)([model, input_new_prime])

predictions = Dense(3)(model)

model = Model(inputs=input_new,outputs=predictions)
opt = keras.optimizers.Adam(lr=0.0001, beta_1=0.9, beta_2=0.999, epsilon=1e-8, decay=1e-5, amsgrad=False)
model.compile(optimizer=opt , loss = loss_space_angle)

print(model.summary())
    

W0820 15:57:04.890130 47630012646720 deprecation.py:506] From /users/PAS1495/amedina/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 9, 60, 86)    0                                            
__________________________________________________________________________________________________
lambda_1 (Lambda)               (None, 74242)        0           input_2[0][0]                    
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 74242)        0           lambda_1[0][0]                   
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 512)          38012416    dropout_1[0][0]                  
__________________________________________________________________________________________________
leaky_re_l

In [12]:
history1 = []
history2 = []
batch_size = 128
epochs=40


history=model.fit(x_train, y_train,
                      batch_size=batch_size,
                      epochs=epochs,
                      verbose=1,
                      validation_data=(x_test, y_test))
history_dict = history.history
history1.append(history_dict['loss'])
history2.append(history_dict['val_loss'])


Train on 17606 samples, validate on 1957 samples
Epoch 1/40
17606/17606 [==============================] - 30s 2ms/step - loss: 0.9193 - val_loss: 0.5195
Epoch 2/40
17606/17606 [==============================] - 29s 2ms/step - loss: 0.4051 - val_loss: 0.3799
Epoch 3/40
17606/17606 [==============================] - 29s 2ms/step - loss: 0.2885 - val_loss: 0.3236
Epoch 4/40
17606/17606 [==============================] - 29s 2ms/step - loss: 0.2254 - val_loss: 0.2886
Epoch 5/40
17606/17606 [==============================] - 28s 2ms/step - loss: 0.1859 - val_loss: 0.2312
Epoch 6/40
17606/17606 [==============================] - 29s 2ms/step - loss: 0.1577 - val_loss: 0.2263
Epoch 7/40
17606/17606 [==============================] - 28s 2ms/step - loss: 0.1369 - val_loss: 0.1878
Epoch 8/40
17606/17606 [==============================] - 29s 2ms/step - loss: 0.1215 - val_loss: 0.1781
Epoch 9/40
17606/17606 [==============================] - 29s 2ms/step - loss: 0.1086 - val_loss: 0.1873
Epoch 

In [13]:
#import matplotlib.pyplot as plt
#history_dict = history.history
#print(history_dict.keys())
#loss_values = history_dict['loss']
#val_loss_values = history_dict['val_loss']

#epochs = range(1, len(loss_values)+1)

#start = 2

#plt.plot(epochs[start:len(epochs)],loss_values[start:len(loss_values)],'bo',label='Training loss')
#plt.plot(epochs[start:len(epochs)],val_loss_values[start:len(val_loss_values)],'b',label='Validation loss')
#plt.title('Training and validation loss')
#plt.xlabel('Epochs')
#plt.ylabel('Loss')
#plt.legend()

#plt.show()

In [14]:
import matplotlib.pyplot as plt
labels = ['128']
count = 0
count1 = 0
epochs = range(1, len(history1[0])+1)
plt.figure()
for i in history1:
    plt.plot(epochs,i,label = labels[count])
    count+=1
for j in history2:
    plt.plot(epochs,j,label=labels[count1])
    count1+=1
plt.legend()
plt.show()

<Figure size 640x480 with 1 Axes>

In [15]:
#plt.savefig('figure.png')